# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='math',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\x12\x04math\"(\n\x10\x43\x61lculateRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0e\x43\x61lculateReply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\x42\n\x03Sum\x12;\n\tCalculate\x12\x16.math.CalculateRequest\x1a\x14.math.CalculateReply\"\x00\x32\x44\n\x05Power\x12;\n\tCalculate\x12\x16.math.CalculateRequest\x1a\x14.math.CalculateReply\"\x00\x42\x0c\n\x04math\x88\x01\x01\x90\x01\x01\x62\x06proto3')
)




_CALCULATEREQUEST = _descriptor.Descriptor(
  name='CalculateRequest',
  full_name='math.CalculateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='math.CalculateRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='math.CalculateRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=63,
)


_CALCULATEREPLY = _descriptor.Descriptor(
  name='CalculateReply',
  full_name='math.CalculateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='math.CalculateReply.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['CalculateRequest'] = _CALCULATEREQUEST
DESCRIPTOR.message_types_by_name['CalculateReply'] = _CALCULATEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalculateRequest = _reflection.GeneratedProtocolMessageType('CalculateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATEREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:math.CalculateRequest)
  ))
_sym_db.RegisterMessage(CalculateRequest)

CalculateReply = _reflection.GeneratedProtocolMessageType('CalculateReply', (_message.Message,), dict(
  DESCRIPTOR = _CALCULATEREPLY,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:math.CalculateReply)
  ))
_sym_db.RegisterMessage(CalculateReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\004math\210\001\001\220\001\001'))

_SUM = _descriptor.ServiceDescriptor(
  name='Sum',
  full_name='math.Sum',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=96,
  serialized_end=162,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='math.Sum.Calculate',
    index=0,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUM)

DESCRIPTOR.services_by_name['Sum'] = _SUM


_POWER = _descriptor.ServiceDescriptor(
  name='Power',
  full_name='math.Power',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=164,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='Calculate',
    full_name='math.Power.Calculate',
    index=0,
    containing_service=None,
    input_type=_CALCULATEREQUEST,
    output_type=_CALCULATEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POWER)

DESCRIPTOR.services_by_name['Power'] = _POWER

Sum = service_reflection.GeneratedServiceType('Sum', (_service.Service,), dict(
  DESCRIPTOR = _SUM,
  __module__ = 'service_pb2'
  ))

Sum_Stub = service_reflection.GeneratedServiceStubType('Sum_Stub', (Sum,), dict(
  DESCRIPTOR = _SUM,
  __module__ = 'service_pb2'
  ))


Power = service_reflection.GeneratedServiceType('Power', (_service.Service,), dict(
  DESCRIPTOR = _POWER,
  __module__ = 'service_pb2'
  ))

Power_Stub = service_reflection.GeneratedServiceStubType('Power_Stub', (Power,), dict(
  DESCRIPTOR = _POWER,
  __module__ = 'service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
